<?php

namespace App\Models;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class AcordoFrete extends Eloquent
{
    protected $table = 'acordos_frete';

    //campos
    protected $fillable = [
        "TESTE1611",
        "FURIA",
        "FAZE",
        "TESTE 1811",
        "LIQUID",
        "G2",
        "TESTECNPJ",
        "TESTE2211",
        "INFOMINAS",
        "INFOTRANS",
        "SHARKS",
        "HULCK",
        "TETOOO",
        "TESTE",
        "TESTE2",
        "TESTE3",
        "TTESTEE",
        "VITALITY",
        "ASTRALIS",
        "NAVI",
        "TETOOO",
        "TESTE",
        "TESTE2",
        "TESTE3",
        "TTESTEE",
        "TRANSMED",
        "FHSO",
        "CASAALADIM",
        "AGILE",
        "VAPTVUPT",
        "CARVALHO",
        "ILS",
        "ASSUNCAO",
        "TOPCESTAS",
        "CLAUDIO",
        "FRETERAPIDO",
        "TETS",
        "NCN",
        "JL",
        "AZAPFY",
        "JC",
        "GS",
        "PHLOG",
        "RODOFAR",
        "DALA",
        "TRANSCARGA",
        "TRANSELLO",
        "TEGMA",
        "JOSEAUGUSTO",
        "FM",
        "RC",
        "TRANSLIDER",
        "TRANSSOARES",
        "AR4D",
        "JR",
        "MM",
        "PG",
        "ACRIPEL",
        "CABRAL",
        "JOBSON",
        "FERREIRA",
        "PONTUAL",
        "SANTACLARA",
        "LOGAKI",
        "TOTAL",
        "AQUILA",
        "TRANSPAPER",
        "FARMIX",
        "EMIS",
        "REDEMINEIRA",
        "GAMA",
        "ROCHA",
        "R2B",
        "ITZ",
        "AJATO",
        "SOMED",
        "NAZARIA",
        "JM",
        "AMB",
        "ALMEIDA",
        "MEDLOG",
        "AACR",
        "JSP",
        "TNORTE",
        "WANDERLEY",
        "TRANSNIL",
        "VAPUTVUPT",
        "FENIX",
        "WF",
        "IZITRANSP",
        'id',
        'nome',
        'ciclo',
        'dt_abertura',
        'dt_fechamento',
        'metodo_calc',
        'ocorrencias',     
        'grupo_emp',
        "tipo_emp",
        'rotas',
        'entregadores',
        'motoristas',
        'timezone'   
    ];


    protected $dates = [];

    protected $hidden = ['_id','updated_at'];

    public $exists = true;
}
