<?php

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Sac extends Eloquent
{
    protected $table = 'sac';

    protected $fillable = [
        "DAMASIO",
        "COMERCIAL",
        "TRANSLIMA",
        "LOGUI",
        "ALMEIDASI",
        "RRTLOG",
        "YASMIN",
        "VELTEN",
        "VDCLOG",
        "BR",
        "PRIMER",
        "TESTE 1811",
        "TESTE 1811",
        "TESTE1611",
        "FURIA",
        "FAZE",
        "TESTE 1811",
        "LIQUID",
        "G2",
        "TESTECNPJ",
        "TESTE2211",
        "INFOTRANS",
        "SHARKS",
        "HULCK",

        "TESTE",
        "TESTE2",
        "TESTE3",
        "TTESTEE",
        "VITALITY",
        "ASTRALIS",
        "NAVI",
        "TETOOO",
        "TESTE",
        "TESTE2",
        "TESTE3",
        "TTESTEE",
        "TRANSMED",
        "FHSO",
        "AGILE",
        "CASAALADIM",
        "VAPTVUPT",
        "IZITRANSP",
        "WFT",
        "VAPUTVUPT",
        "FENIX",
        "FONSECA",
        "WANDERLEY",
        "AACR",
        "TNORTE",
        "MEDLOG",
        "AACARVALHO",
        "JSP",
        "ALMEIDA",
        "WF",
        "R2B",
        "ITZ",
        "NAZARIA",
        "INFODEC",
        "TOTAL",
        "YM",
        "ROCHA",
        "LOGAKI",
        "SANTACLARA",
        "PONTUAL",
        "MM",
        "PG",
        "JOBSON",
        "PONTUALCARGA",
        "M&M",
        "JOSEAUGUSTO",
        "FM",
        "RC",
        "TRANSLIDER",
        "TRANSSOARES",
        "AR4D",
        "OFFICE",
        "PACOTE",
        "EXPRESSO",
        "TRANSELLO",
        "TEGMA",
        "CLAUDIO",
        "PREPOC",
        "DOCTESTE",
        "TETS",
        "TESTEZITO JR",
        "TRANSDONATTO",
        "TESTSE",
        "GSFARMA",
        "GS",
        "DALA",
        "MARTINS",
        "ELOG",
        "TRANSCARGA",
        "JPR",
        "SAMEX",
        "ZUUM",
        "MARTINS",
        "ELOG",
        "BIKER",
        "RODOFAR",
        "AZAPFYESAS",
        "REDEMINEIRA",
        "AMB",
        "FERREIRA",
        "ILS",
        "3GLOG-1",
        "PHLOG",
        "TRANSPAPER",
        "FARMIX",
        "CIMED",
        "CARVALHO",
        "AJATO",
        "JL",
        "CABRAL",
        "CMAXX",
        "JM",
        "AQUILA",
        "ESCOLHA",
        "INFOMINAS",
        "JR",
        "SILVEIRA",
        "MG_MEDICAL",
        "TOPCESTAS",
        "EMIS",
        "JC",
        "3GLOG",
        "DCENTER",
        "AZAPFY",
        "ACRIPEL",
        "GAMA",
        "NCN",
        "ORIENTE",
        "TRANSNIL",
        "DNG",
        "SOMED",
        "ASSUNCAO",
        "FRETERAPIDO",
        "PH",

        "protocolo",
        "nome_relator",
        "cod_relator",
        "contato_relator",
        "responsaveis",
        "nome_responsavel",
        "cod_responsavel",
        "contato_responsavel",
        "dt_abertura",
        "atribuido",
        "grupo_emp",
        "dt_atendimento",
        "incidente",
        "doc",
        "status",
        "chat",
        "anexos",
        "dt_resolucao",
        "feedback"
    ];

    protected $dates = [];
    protected $hidden = ['_id'];
    public $exists = true;
}
